### ISSUE TITLE
 Class 'Faker' not found 

### ISSUE THREAD

**Issue by mohsenmehri6101** [Ybazli/faker#10]
How to use this package in the controller?
I can use this package in seeders,but in controller show this error : 
`class PFaker Not found`
Although i,m add this app.php : 
`
//providers 
Ybazli\Faker\FakerServiceProvider::class,
//aliases
'PFaker' => Ybazli\Faker\Facades\Faker::class,
`
i,m define name PFaker instead Faker

**Comment by Ybazli** [comment]
Hey @mohsenmehri6101, in the controller you can use like below:
```php
use Ybazli\Faker\Faker;

class testController extends Controller
{
    public function test()
    {
        return (new Faker())->firstName();
    }
}
```
or:
```php
use Ybazli\Faker\Faker;

class testController extends Controller
{
    private $faker;

    public function __construct()
    {
        $this->faker = new Faker();
    }

    public function test()
    {
        return $this->faker->fullName();
    }
}
```
If this code block helps you please don't forget to close this issue. 
Happy Coding
