### ISSUE TITLE
must be an instance of Ybazli\Faker\Facades\Faker, instance of Faker\Generator given

### ISSUE THREAD

**Issue by saber13812002** [Ybazli/faker#12]
i cant use faker in laravel 7

my error is

`must be an instance of Ybazli\Faker\Facades\Faker, instance of Faker\Generator given
`

**Comment by Ybazli** [comment]
@saber13812002 can you share your code block here?

**Comment by saber13812002** [comment]
i just install it on my laravel 

and after this error 

i undeerstand that i can configure faker for persian by editing

APP CONFIG

```

Faker locale can be configured in the config/app.php configuration file. Just add the key faker_locale.

e.g.: 'faker_locale' => 'fr_FR',

```


`e.g.: 'faker_locale' => 'fa_IR',
`

and its worked thank you
