### ISSUE TITLE
Call to undefined function Ybazli\Faker\str_random()

### ISSUE THREAD

**Issue by alirezajavanmardi** [Ybazli/faker#13]
Call to undefined function Ybazli\Faker\str_random()
 when i want to run my seeders bunch of errors come to me .
this is one of them . why are these happening ?

**Comment by Ybazli** [comment]
in the laravel 7+ the str_random helper was deleted and can callable with Str facade. I'm working on version 2 of this package and will fix this issue in the new version. Feel free to send a pull request for this issue. 
example code for str_random function helper is:
`Str::random();`
Thanks for your feedback. :)
