### ISSUE TITLE
Generating invalid phone numbers

### ISSUE THREAD

**Issue by Nevercom** [Ybazli/faker#7]
In some cases the generated phone number has an extra 0 at the end, which adds up to 12 characters, which is an invalid phone number.

I think the problem is in this line:
https://github.com/Ybazli/faker/blob/3ef7d3a587ff847c0162c6d32d109a8c9a8d3ad8/src/Faker.php#L118

Since `rand()` is inclusive, the max number should be 9.

**Comment by Ybazli** [comment]
Hey @Nevercom, First thank you for reporting this issue.  I tested and it seems true. I'm gonna fix this issue as soon as possible.
